-- MySQL Script generated by MySQL Workbench
-- 10/05/17 00:28:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tblPrices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tblPrices` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tblPrices` (
  `fltTotalPrice` FLOAT NOT NULL,
  `fltClothesPrice` FLOAT NOT NULL,
  `fltBeddingsPrice` FLOAT NOT NULL,
  PRIMARY KEY (`fltTotalPrice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblWeight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tblWeight` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tblWeight` (
  `fltTotalWeight` FLOAT NOT NULL,
  `fltClothesWeight` FLOAT NOT NULL,
  `fltBeddingsWeight` FLOAT NOT NULL,
  PRIMARY KEY (`fltTotalWeight`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblStaff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tblStaff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tblStaff` (
  `strStaffCode` VARCHAR(45) NOT NULL,
  `strLastName` VARCHAR(45) NOT NULL,
  `strFirstName` VARCHAR(45) NOT NULL,
  `strMiddleInitial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`strStaffCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tblOrder` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tblOrder` (
  `strReferenceNumber` VARCHAR(45) NOT NULL,
  `strReceivedDate` VARCHAR(45) NOT NULL,
  `strDispatchDate` VARCHAR(45) NOT NULL,
  `strName` VARCHAR(45) NOT NULL,
  `strStatus` VARCHAR(45) NOT NULL,
  `tblPrices_intTotalPrice` FLOAT NOT NULL,
  `tblWeight_intTotalWeight` FLOAT NOT NULL,
  `strIsHandWashed` VARCHAR(45) NOT NULL,
  `tblStaff_strStaffCode` VARCHAR(45) NOT NULL,
  `intTotalPieces` INT NOT NULL,
  PRIMARY KEY (`strReferenceNumber`, `tblPrices_intTotalPrice`, `tblWeight_intTotalWeight`, `tblStaff_strStaffCode`),
  INDEX `fk_tblOrder_tblPrices_idx` (`tblPrices_intTotalPrice` ASC),
  INDEX `fk_tblOrder_tblWeight1_idx` (`tblWeight_intTotalWeight` ASC),
  INDEX `fk_tblOrder_tblStaff1_idx` (`tblStaff_strStaffCode` ASC),
  CONSTRAINT `fk_tblOrder_tblPrices`
    FOREIGN KEY (`tblPrices_intTotalPrice`)
    REFERENCES `mydb`.`tblPrices` (`fltTotalPrice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblOrder_tblWeight1`
    FOREIGN KEY (`tblWeight_intTotalWeight`)
    REFERENCES `mydb`.`tblWeight` (`fltTotalWeight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblOrder_tblStaff1`
    FOREIGN KEY (`tblStaff_strStaffCode`)
    REFERENCES `mydb`.`tblStaff` (`strStaffCode`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tblLogin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tblLogin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tblLogin` (
  `strPassword` VARCHAR(45) NOT NULL,
  `tblStaff_strStaffCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`strPassword`, `tblStaff_strStaffCode`),
  INDEX `fk_tblLogin_tblStaff1_idx` (`tblStaff_strStaffCode` ASC),
  CONSTRAINT `fk_tblLogin_tblStaff1`
    FOREIGN KEY (`tblStaff_strStaffCode`)
    REFERENCES `mydb`.`tblStaff` (`strStaffCode`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
